// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsxTest")>]
[<assembly: AssemblyProductAttribute("FsxTest")>]
[<assembly: AssemblyDescriptionAttribute("testing fsx and F# 4.1")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsxTest"
    let [<Literal>] AssemblyProduct = "FsxTest"
    let [<Literal>] AssemblyDescription = "testing fsx and F# 4.1"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
